### ISSUE TITLE
a quick question

### ISSUE THREAD

**Issue by Ever4engel** [YuJianrong/extensions#4]
...

**Comment by YuJianrong** [comment]
it's intentional to keep a low profile for these tools so I'll answer your question but delete my answer 10 mins later. Hope you can get this message from your Email Notification.
The proper way to use these extensions is: open chrome extensions page by visiting: `chrome://extensions/`, check `Developer mode` (top right), then drag `xxxxExtension.zip` to the extensions page. The extension will be installed and most download scripts should be working properly.

**Warning: Do it at your own risk. Technically any code can be run by this way on any page, there is a very big security risk to run third-party extension (and of course include mine), there are a few tricks used in these extensions which will bring more security risks in your browser. I don't take any responsibility for your loss. Suggest do not use it in your everyday use browser.**

**Comment by Ever4engel** [comment]
@YuJianrong can you please answer me when you have time ^^?

**Comment by YuJianrong** [comment]
> @YuJianrong can you please answer me when you have time ^^?

I guess you disabled the Email notification so missed my reply. I'll paste here again:

> It's intentional to keep a low profile for these tools so I'll answer your question but delete my answer soon. Hope you can get this message from your Email Notification.
> The proper way to use these extensions is: open chrome extensions page by visiting: `chrome://extensions/`, turn on Developer mode (top right), then drag `xxxxExtension.zip` to the extensions page. The extension will be installed and most download scripts should be working properly. Note: most of the extensions work on one-page mode only.
> 
> **Warning: Do it at your own risk. Technically any code can be run by this way on any page, there is a very big security risk to run third-party extension (and of course include mine), there are a few tricks used in these extensions which will expose your browser in security risks. I don't take any responsibility for your loss. Suggest do not use it in your everyday use browser or disable/remove the extension after use.**

Please close this ticket when you read this message. I'll delete it once it's closed.

**Comment by Ever4engel** [comment]
thanks !!

**Comment by YuJianrong** [comment]
> Btw i use Edge (the chrome fork) and as i said when i inject tongli script in the console it work.
> 
> if you have a discord account, we can talk more privately :) mine is EvEr4EnGeL#4846

As I mentioned, **most of the extensions work on one-page mode only**. Please narrow your browser window to change it to one page mode (if it's not resizable to a narrow size, please open dev-tools so the main browser content will be narrower to trigger the one-page mode).

Some of the extensions may not work if the website upgraded, I'll fix them when I have time. Please report to me if it's not working in **one-page** mode, thanks.

**Comment by Ever4engel** [comment]
> Some of the extensions may not work if the website upgraded, I'll fix them when I have time. Please report to me if it's not working in **one-page** mode, thanks.

oohhh okey it work on my side. thanks for your answer ^^
